SHOW DATABASES;
USE WORLD;
SELECT * FROM CITY;
-- USE OF WHERE AND GROUP BY
SELECT DISTRICT, COUNT(NAME) FROM CITY WHERE POPULATION>100000 GROUP BY DISTRICT;
SELECT * FROM COUNTRY;
SELECT CONTINENT, COUNT(NAME) FROM COUNTRY WHERE INDEPYEAR>1950 GROUP BY CONTINENT;
-- WHERE ONLY FILTER THE DATA WHICH IS AVILABLE IN MY TABLE
-- IF CAN'T ACTION ON SUM POPULATION FOR ANY OPERATION: 
SELECT CONTINENT, SUM(POPULATION) FROM COUNTRY GROUP BY CONTINENT;
SELECT CONTINENT, COUNT(INDEPYEAR) FROM COUNTRY GROUP BY CONTINENT;
-- WHERE CLAUSE IS USED TO FILTER THE DATA IN TABLE:
-- HAVING IS FILTER THE DATA ON AGRIGATE COLOUMN:
-- HAVING TO FILTER BASED ON COLOUMN LIKE SUM, COUNT, MAX:
SELECT CONTINENT, SUM(POPULATION) FROM COUNTRY GROUP BY CONTINENT HAVING SUM(POPULATION)>40000000;

SELECT * FROM COUNTRY;
-- SELECT CONTINENT, SUM(POPULATION) FROM COUNTRY WHERE LIFEEXPECTANCY>35;
-- QUESTIONS:
-- FIND TOTAL NUMBER OF COUNTRY AND  GOVERMENTFORM WHERE COUNTRY HAVE GOVERMENTFORM >30:
-- FIND TOTAL NUMBER OF COUNTRY AND GOVERMENTFORM ONLY FOR A COUNTRY HVAING THEIR CAPITAL GRATER THAT 30 AND TOTAL POPULATION GRATER THEN 3 LAKH

SELECT GOVERNMENTFORM, COUNT(NAME) FROM COUNTRY GROUP BY GOVERNMENTFORM HAVING COUNT(NAME)>30;
SELECT GOVERNMENTFORM, COUNT(NAME),SUM(POPULATION) FROM COUNTRY WHERE CAPITAL>30 GROUP BY GOVERNMENTFORM HAVING SUM(POPULATION)>30000;

-- DOUBLE GROUP BY
SELECT CONTINENT REGION, COUNT(NAME) FROM COUNTRY GROUP BY CONTINENT,REGION;


		